[package]
name = "tokio-syslog"
version = "0.1.0"
authors = ["Alexander Polyakov <apolyakov@beget.com>"]

[dependencies]
futures = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"
tokio-io = "0.1"
tokio-uds = "0.1"
bytes = "0.4"

[dev-dependencies]
tokio-core = "0.1"
tokio-uds-proto = "0.1"
